apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apne1-foobar
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  # The project the application belongs to.
  project: default

  # Source of the application manifests
  source:
    repoURL: 'https://github.com/liaodaniel/k8s_app_of_apps.git'
    targetRevision: HEAD
    path: clusters/apne1/barfoo

    kustomize:
      namePrefix: apne1-
  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      # Specifies if resources should be pruned during auto-syncing ( false by default ).
      selfHeal: true
      # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
    validate: true
    # Validate resources before applying to k8s, defaults to true.
