---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: foobar-apache
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "0"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: foobar-nginx
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "1"
---
